fabien0102/openapi-codegen

cli/src/commands/GenerateCommand.ts

`import path from "path/posix"` doesn't work on node 14.
Closed #33

fix: Fix `path` usage for node 14

---

plugins/typescript/src/core/schemaToTypeAliasDeclaration.test.ts
plugins/typescript/src/core/schemaToTypeAliasDeclaration.ts

Specs containing `*/` are producting non valid code.
Closed #57 
Closed #36

fix: Fix comment generation

---

plugins/typescript/src/core/createNamedImport.ts
plugins/typescript/src/core/getUsedImports.test.ts
plugins/typescript/src/core/getUsedImports.ts
plugins/typescript/src/generators/generateFetchers.test.ts
plugins/typescript/src/generators/generateReactQueryComponents.test.ts

Hi,
Really nicely thought-out tool!
The project we would like to use it with has `"importsNotUsedAsValues"` set to `error` in `tsconfig.json`. Therefore the generated 
```
import { ClientErrorStatus, ServerErrorStatus } from './<prefix>Utils';
```
causes an error in Typescript.

fix: Fixed ServerErrorStatus, ClientErrorStatus not being imported as type

---

plugins/typescript/src/templates/fetcher.ts

Support for FormData in the TS fetcher generator.
At the moment, if you pass in FormData as the body, (and manually set headers to  "Content-Type": "multipart/form-data") the body is stringified. This breaks posting FormData as the object should not be stringified.

Support FormData in the TS fetcher generator

---

plugins/typescript/src/core/schemaToTypeAliasDeclaration.test.ts
plugins/typescript/src/core/schemaToTypeAliasDeclaration.ts

I have fixed the problem of `null` is not included in the union when converting nullable enums.
Input:
```yml
test:
type: string
enum: [foo, bar, baz]
nullable: true
```
Expect:
```ts
export type Test = "foo" | "bar" | "baz" | null;
```
Actual:
```ts
export type Test = "foo" | "bar" | "baz";
```

fix: Support for nullable enums

---

plugins/typescript/src/core/getParamsGroupByType.ts
plugins/typescript/src/core/isRequestBodyOptional.test.ts
plugins/typescript/src/core/isRequestBodyOptional.ts

Instead of `get(foo, "a.b.c")` use `get(foo, ["a", "b.c"])`

fix: Allow components to have dots in their names

---

plugins/typescript/src/core/schemaToTypeAliasDeclaration.ts

In cases such as `additionalProperties: false`

fix: Check that property is an object

---

cli/package.json
cli/src/commands/GenerateCommand.ts
cli/src/commands/InitCommand.ts
package-lock.json
package.json

For some reason, the Prettier version on the cli package is 2.8.8
https://npmgraph.js.org/?q=@openapi-codegen/cli#select=exact%3Aprettier%402.8.8
This PR updated it to current latest

fix: Update prettier version to 3.2.5

---

cli/src/core/getOpenAPISourceFile.ts

As github graphql has body size limitation due to which large spec files gets trim and validation fails the generation so switched the reading of file form github graphql api to rest api as it doesn't have the same limitation of content reading 
This PR resolve this [issue](https://github.com/fabien0102/openapi-codegen/issues/251)

fix: Changed Read API Method for Github from Graphql API to Rest API

---

cli/rollup.config.js
package-lock.json

Addresses [issue#264](https://github.com/fabien0102/openapi-codegen/issues/264).
Changes to `package-lock.json` are just the versions of "@openapi-codegen/cli" to "2.0.3" and "@openapi-codegen/typescript" to "8.1.0", result of running "npm i".

fix(cli): update rollup config

---

plugins/typescript/src/core/schemaToEnumDeclaration.test.ts
plugins/typescript/src/core/schemaToTypeAliasDeclaration.test.ts
plugins/typescript/src/core/schemaToTypeAliasDeclaration.ts

Generating enums using the useEnums option will generate the enum types with `pascal(name)`, however when referencing the enum type, the name is not formatted.
This causes issues with lowerCamelCase names.
Wrapping `name || ""` inside a `pascal` solves issues with lowerCamelCase names.

fix: Fix pascal enum reference

---

plugins/typescript/src/templates/fetcher.ts

Currently when a request goes wrong (essentially when `!response.ok`) we always end up with some sort of `Network Error`, which is not the desired behavior when the spec and the generated typing expects us to have a `<RequestSecifc>Error`.
As this issue isn't new and has been solved in comments by [SeanCondon](https://github.com/SeanCondon) as well as [MarcusOhman91](https://github.com/MarcusOhman91) already this is more of a paperwork PR.
Closes #188
Closes #113

fix: properly handle request errors

---

plugins/typescript/src/core/schemaToTypeAliasDeclaration.test.ts
plugins/typescript/src/core/schemaToTypeAliasDeclaration.ts

When a description includes `*/`, this is causing a broken generated multiline comment, let’s strip them in a smart way to avoid this issue.
Example in github specs:
```yaml
deployment-branch-policy-name-pattern:
properties:
name:
description: |-
The name pattern that branches must match in order to deploy to the environment.
Wildcard characters will not match `/`. For example, to match branches that begin with `release/` and contain an additional single slash, use `release/*/*`.
For more information about pattern matching syntax, see the [Ruby File.fnmatch documentation](https://ruby-doc.org/core-2.5.1/File.html#method-c-fnmatch).
example: release/*
type: string
required:
- name
title: Deployment branch policy name pattern
type: object
```
The `release/*/*` will close the generated …

fix: Deal with forbidden chars in description

---

plugins/typescript/src/generators/generateFetchers.ts
plugins/typescript/src/generators/generateReactQueryComponents.ts
plugins/typescript/src/generators/generateReactQueryFunctions.ts
plugins/typescript/src/generators/generateSchemaTypes.ts
plugins/typescript/src/generators/types.ts

I have a special need where I want to add `.gen` at the end of the files that are always regenerated by the codegen.
Instead of baking that logic into this lib, I thought that allowing to provide a custom formatter would be generic enough and I can do a mapping on my side like this
```ts
const formatFilename = (filename: string) => {
filename = _.kebabCase(filename);
const needsDotGen = [
`${filenamePrefix}-components`,
`${filenamePrefix}-request-bodies`,
`${filenamePrefix}-schemas`,
`${filenamePrefix}-parametersF`,
`${filenamePrefix}-responses`,
].includes(filename);
return `${filename}${needsDotGen ? ".gen" : ""}`;
};
const { schemasFiles } = await generateSchemaTypes(context, {
filenamePrefix,
formatFilename,
});
await generateReactQueryComponents(context, {
schemasFiles, …
```

feat: Added config formatFilename to allow more custom formatting of filenames

---

plugins/typescript/src/templates/fetcher.ts

Fixes an error introduced by #260
Error variable was still initialized inside the try-catch block but throw was moved outside.
I just moved the initialization to the top of the function similar to #188

fix: Invalid variable access inside fetcher

---

plugins/typescript/src/core/schemaToTypeAliasDeclaration.test.ts
plugins/typescript/src/core/schemaToTypeAliasDeclaration.ts

If there are multiple discriminator keys pointing to the same schema object, only the first discriminator is currently used for the generated code.
This change will add a string union to the Omit definition and will check for all enum values if it is compliant with the original type.

fix: Fix multiple discriminator on same type

---

examples/frontend/src/github/githubComponents.ts
examples/frontend/src/github/githubUtils.ts
plugins/typescript/src/generators/generateReactQueryComponents.test.ts
plugins/typescript/src/generators/generateReactQueryComponents.ts
plugins/typescript/src/templates/utils.test.ts
plugins/typescript/src/templates/utils.ts

Following up on my comment [here](https://github.com/fabien0102/openapi-codegen/pull/286#issuecomment-2647849457).
Did not change the merge function I proposed but I additionally removed skipToken as possible input as I don't think it would output the skipToken as a result of the deepMerge function, as when I tested it in the browser using `Object.assign({ header: {} }, Symbol("Test"))` it returned `{ header: {} }` instead of `Symbol("Test")`.
Also updated the example again as I anyway use it to verify.

chore: Improve deepMerge typing and removed skipToken as possible input

---

plugins/typescript/src/core/schemaToTypeAliasDeclaration.test.ts
plugins/typescript/src/core/schemaToTypeAliasDeclaration.ts

`{type: "object", additionalProperties: false}` should generate `Record<string, never>` instead of `Record<string, any>` (free form object vs empty object)
Closed #258

fix: Deal with empty object generation

---

cli/src/core/getOpenAPISourceFile.ts

Github strips large file, we need to use the `raw` media type to avoid this issue
From github specs
https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28
> If the requested file's size is:
> * 1 MB or smaller: All features of this endpoint are supported.
> * Between 1-100 MB: Only the raw or object custom media types are supported. Both will work as normal, except that when > using the object media type, the content field will be an empty string and the encoding field will be "none". To get the contents of these larger files, use the raw media type.
> * Greater than 100 MB: This endpoint is not supported.

feat: handle large specs

---

README.md

Tanstack has somewhat recently rearranged their documentation, causing some old pages to 404. This addresses that, as well as drops in a link to the React Query lib install page, which covers different options for installing depending on project setup.
README change from this:
To this:

doc: Update links to React Query in README
